allSales/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from . import settings
from .views import MainView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^rma/', include('rma.urls', namespace='rma')),
    url(r'^prio/', include('prioListe.urls', namespace='pListe')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^statistic/', include('statistic.urls', namespace='statistic')),
    url(r'^warranty/', include('warranty.urls', namespace='warranty')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prioListe/urls.py
from django.conf.urls import url
from . import views
from .views import UpdateAssignment
from .views import UpdatedProduction
from .views import UpdateAssignmentWithoutBox
from .views import UpdateDoneAssignment

app_name = 'pListe'
urlpatterns = [
    url(r'^prioListe/', views.show_list, name='home'),
    url(r'^missingbelts/$', views.show_missing_belts, name='belts'),
    url(r'^missingbatteries/$', views.show_missing_batteries, name='batterie'),
    url(r'^create/$', views.create_assignment_entry, name='create'),
    url(r'^update/(?P<pk>[\d]+)/$', UpdateAssignment.as_view(), name='update'),
    url(r'^update_withou_box/(?P<pk>[\d]+)/$', UpdateAssignmentWithoutBox.as_view(), name='update_without_box'),
    url(r'^update_box/(?P<pk>[\d]+)/$', views.update_box, name='update_box'),
    url(r'^update_belt/(?P<pk>[\d]+)/(?P<path>.*)/$', views.update_belt, name='update_belt'),
    url(r'^update_batterie/(?P<pk>[\d]+)/(?P<path>.*)/$', views.update_batterie, name='update_batterie'),
    url(r'^update_assembled/(?P<pk>[\d]+)/(?P<path>.*)/$', views.update_assembled, name='update_assembled'),
    url(r'^update_electric/(?P<pk>[\d]+)/(?P<path>.*)/$', views.update_electronic, name='update_electric'),
    url(r'^updateProduction/(?P<pk>[\d]+)/$', UpdatedProduction.as_view(), name='updateProduction'),
    url(r'^batterie/(?P<path>.*)/$', views.show_specifc_batterie_type, name='hardware_batterie'),
    url(r'^update_batterie_shelf/(?P<pk>[\d]+)/$', views.update_batterie_shelf, name='update_batterie_shelf'),
    url(r'^update_belt_shelf/(?P<pk>[\d]+)/$', views.update_belt_shelf, name='update_belt_shelf'),
    url(r'^update_electric_shelf/(?P<pk>[\d]+)/$', views.update_electric_shelf, name='update_electric_shelf'),
    url(r'^search_all/(?P<path>.*)/$', views.search_form, name='prio_search'),
    url(r'^prioListe_done', views.show_finished_list, name='done'),
    url(r'^update_comment/(?P<pk>[\d]+)/$', UpdateDoneAssignment.as_view(), name='update_comment_only'),
    url(r'^notice_delete/(?P<pk>[\d]+)/$', views.notice_about_delete, name='delete_notice')
]

rma/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from allSales import settings
from . import views
from .views import RefurbishmentFormView
from .views import RefurbishmentUpdateView
from .views import RMADelete

app_name = 'rma'
urlpatterns = [
    url(r'^$', views.refurbishment_list, name='home'),
    url(r'^create/$', RefurbishmentFormView.as_view(), name='create'),
    url(r'^update/(?P<pk>[\d]+)$', RefurbishmentUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[\d+]+)$', RMADelete.as_view(), name='delete'),
    url(r'^search/$', views.search_customer, name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prioListe/models.py
from django.db import models
from datetime import datetime

from django.urls import reverse

from staff.models import Staff

from .utils import get_choices
from .utils import COLORS
from .utils import STAFFCHOICESONE


def upload_record_path(instance, filename):
    if instance.ordering_number is not None:
        return '/'.join(['media', instance.ordering_number, filename])
    else:
        return '/'.join(['media', instance.staff + str(instance.internal_progress_number), filename])


class StaffColor(models.Model):
    class Meta:
        managed = True
        app_label = 'prioListe'

    name = models.CharField(max_length=255, choices=STAFFCHOICESONE)
    color = models.CharField(max_length=255, null=False, blank=False, default='#000000')


class PriolisteAssignment(models.Model):
    class Meta:
        ordering = ['finished_until']
        managed = True
        app_label = 'prioListe'

    status = models.CharField(max_length=20, choices=get_choices(), blank=True, null=True)
    finished_until = models.DateField(null=True)
    staff = models.CharField(max_length=10, null=False)
    co_worker = models.CharField(max_length=10, null=False, blank=True)
    time_in_weeks = models.IntegerField(null=True)
    box = models.CharField(max_length=255, null=True, blank=True, help_text='Not longer required')
    customer = models.CharField(max_length=255, null=True)
    hardware = models.TextField(null=True, blank=True)
    optional_status = models.CharField(max_length=200, null=True, blank=True)
    production_remark = models.TextField(null=True, blank=True)
    changed = models.BooleanField(default=False)
    remark = models.TextField(null=True, blank=True)
    assembled = models.BooleanField(default=False, blank=True)
    batterie = models.BooleanField(default=False, blank=True)
    belt = models.BooleanField(default=False, blank=True)
    elektronic = models.BooleanField(default=False, blank=True)
    drop_off = models.BooleanField(default=False, blank=True)
    last_change = models.DateField(blank=True, null=True)
    created_at = models.DateField(default=datetime.today())
    ordering_number = models.CharField(max_length=255, blank=True, null=True)
    internal_progress_number = models.PositiveIntegerField(default=-1)
    prod_rec_one = models.FileField(blank=True, null=True, upload_to=upload_record_path)
    prod_rec_two = models.FileField(blank=True, null=True, upload_to=upload_record_path)
    prod_rec_three = models.FileField(blank=True, null=True, upload_to=upload_record_path)
    prod_rec_four = models.FileField(blank=True, null=True, upload_to=upload_record_path)
    prod_rec_five = models.FileField(blank=True, null=True, upload_to=upload_record_path)
    prod_rec_string = models.CharField(max_length=300, blank=True, null=True)
    has_box = models.BooleanField(default=False, blank=True)
    changed_by_ip = models.CharField(max_length=255, default='0.0.0.0')
    ids = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.ordering_number)

    def get_main_root(self):
        return reverse('pListe:home')

    def get_labelname(self):
        return 'To Priority-List'

    def get_second_root(self):
        return reverse('pListe:done')

    def get_second_labelname(self):
        return 'To Shippingboard'

    def get_update_url(self):
        return reverse('pListe:update', kwargs={
            'pk': self.pk,
        })

    def get_box_update_url(self):
        return reverse('pListe:update_box', kwargs={
            'pk': self.pk,
        })

    def get_box_update_number_url(self):
        return reverse('pListe:update_box_number', kwargs={
            'pk': self.pk,
        })

    def get_update_without_box(self):
        return reverse('pListe:update_without_box', kwargs={
            'pk': self.pk,
        })

    def get_update_production(self):
        return reverse('pListe:updateProduction', kwargs={
            'pk': self.pk,
        })

    def get_shelf(self):
        return Shelf.objects.filter(assignment=self)

    def update_batterie_shelf(self):
        return reverse('pListe:update_batterie_shelf', kwargs={
            'pk': self.pk,
        })

    def update_belt_shelf(self):
        return reverse('pListe:update_belt_shelf', kwargs={
            'pk': self.pk,
        })

    def update_electric_shelf(self):
        return reverse('pListe:update_electric_shelf', kwargs={
            'pk': self.pk,
        })

    def create_productionrecord_reversed(self):
        return reverse('sales:prodrecpdf_fromprioliste', kwargs={
            'pk': self.pk,
            'progress_number': self.internal_progress_number,
        })

    def get_comment_update_only(self):
        return reverse('pListe:update_comment_only', kwargs={
            'pk': self.pk,
        })

    def get_delete_notice(self):
        return reverse('pListe:delete_notice', kwargs={
            'pk': self.pk,
        })

    def get_color(self):
        '''
        :return:
        '''
        color = '#ffffff'
        optional_stat = 'in Bearbeitung'
        choices = [i[0] for i in get_choices()]
        if self.status in choices:
            color = COLORS[self.status]
        elif self.optional_status is not None:
            if self.optional_status in optional_stat:
                color = COLORS['Bearbeitung']
        return color

    def get_staff_color(self):
        staff_color = StaffColor.objects.get(name=self.staff)
        return staff_color.color


class Shelf(models.Model):
    class Meta:
        managed = True
        app_label = 'prioListe'
    shelf_type = models.CharField(max_length=100)
    compartment = models.CharField(max_length=255, blank=True, null=True)
    assignment = models.ForeignKey(PriolisteAssignment)


class ProductionTime(models.Model):
    class Meta:
        managed = True
        app_label = 'prioListe'
    time_in_weeks = models.IntegerField(default=12)
    enabled = models.BooleanField(default=False)
    comment = models.TextField(blank=True, null=True)

rma/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse

from collar.models import Staff

CHOICES = [
    ('', ''),
]
for staff in Staff.objects.all():
    CHOICES.append((staff.name, staff.name))


def file_upload_path(instance, filename):
    return '/'.join(['media', instance.salesPerson, filename])


class Status(models.Model):
    name = models.TextField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'status'
        app_label = 'rma'


class RMAFile(models.Model):
    rma_file = models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')

    class Meta:
        db_table = 'rmafiles'
        app_label = 'rma'


class Refurbisment(models.Model):
    rma = models.TextField(max_length=200)
    salesPerson = models.CharField(max_length=100, choices=CHOICES)
    customer_forename = models.TextField(max_length=200, default='Forename')
    customer_name = models.TextField(max_length=200, default='Surname')
    customer_email = models.EmailField()
    country = models.TextField(max_length=200)
    content = models.TextField(max_length=750, null=True, blank=True)
    parcel_received = models.DateField(blank=True, default=datetime.strptime('2000-01-01', '%Y-%m-%d'))
    comments = models.TextField(max_length=750, null=True, blank=True)
    status = models.ForeignKey(to=Status)
    rma_file = models.FileField(null=True, blank=True, upload_to=file_upload_path)
    rma_second_file = models.FileField(null=True, blank=True, upload_to=file_upload_path)
    shelf = models.PositiveIntegerField(null=True, blank=True)
    #more_files = models.CharField(null=True, blank=True, max_length=255)

    def get_update_url(self):
        return reverse('rma:update',
                       kwargs={'pk': self.pk})

    def get_main_root(self):
        return reverse('rma:home')

    def get_labelname(self):
        return 'To RMA-List'

    def get_delete_url(self):
        return reverse('rma:delete', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'refurbisment'
        ordering = ['status']
        app_label = 'rma'

prioListe/templates/assignment_done_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load extra_tags %}
{% block title %}
    <title>Shipping Board</title>
{% endblock %}
{% block content %}
    <div>
        <p class="col-md-12 col-lg-12 fixed-search">
        <span>
            <a href="{% url 'pListe:home' %}" class="btn btn-info btn-sm" style="float:left; ">Back to Prio-Liste</a>
            <a href="{% url 'main' %}" class="btn btn-info btn-sm" style="float:right; ">Back to Main-Page</a>
        </span>
        </p>
        <div style="margin-bottom:1%;" class="fixed-search col-md-12 col-lg-12">
            <form method="post" action="{% url 'pListe:prio_search' request.path %}" style="float:right; display: inline-grid; background-color:white">
                {% csrf_token %}
                {{ prio_search.as_p }}
                <input type="submit" value="Search/Clear" class="btn btn-dark btn-sm">
            </form>
            <form method="post" action="{% url 'pListe:hardware_batterie' request.path %}" style="display: inline-grid; background-color:white">
                {% csrf_token %}
                {{ batterie_search.as_p }}
                <input type="submit" value="Search/Clear" class="btn btn-dark btn-sm">
            </form>
        </div>
        <div class="col-md-offset-12 col-lg-offset-12" style="z-index: 2; float: left">
            <button id="back-to-top" class="btn btn-info" style="position: fixed; z-index: 3; margin-left: -4%;">To Top</button>
        </div>

        <table id="demo-table" class="table table-bordered tablesorter my-table col-md-12 col-lg-12">
            <thead>
                <tr>
                    <th id="letsGo">Progress Nr.</th>
                    <th>{% trans "Kunde" %}</th>
                    <th>{% trans "Hardware" %}</th>
                    <th>created at</th>
                    <th class="resizable">{% trans "Ansprech" %}-<br>{% trans "partner" %}</th>
                    <th>Comment</th>
                    <th>Vnr</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                    <tr style="background-color:{{ object.get_staff_color }}">
                    <td class="box-nr" scope="row"><p>
                            {{ object.internal_progress_number }}
                    </p></td>
                    <td id='column-header-9'>{{ object.customer }}</td>
                    <td id='column-header-8'>{{ object.hardware|safe|wordwrap:10 }}</td>
                    <td id='column-header-11'>{{ object.last_change|date:"d.m.y" }}</td>
                    <td id='column-header-4'>{{ object.staff }}
                    {% if object.co_worker|length > 1 %}
                        / {{ object.co_worker }}
                    {% endif %}
                    </td>
                    <td id='column-header-2' class="remark remark_number_{{ forloop.counter0 }}">{% if object.remark == None %}
                        &nbsp;
                        {% else %}
                            {{ object.remark|wordwrap:3 }}
                        {% endif %}
                        {% if object.prod_rec_one %}
                            <a href="/media/{{ object.prod_rec_one }}">{{ object.prod_rec_one|cut_string }}</a>
                        {% endif %}
                        {% if object.prod_rec_two %}
                            <br>
                            <a href="/media/{{ object.prod_rec_two }}">{{ object.prod_rec_two|cut_string }}</a>
                        {% endif %}
                        {% if object.prod_rec_three %}
                            <br>
                            <a href="/media/{{ object.prod_rec_three }}">{{ object.prod_rec_three|cut_string }}</a>
                        {% endif %}
                        {% if object.prod_rec_four %}
                            <br>
                            <a href="/media/{{ object.prod_rec_four }}">{{ object.prod_rec_four|cut_string }}</a>
                        {% endif %}
                        {% if object.prod_rec_five %}
                            <br>
                            <a href="/media/{{ object.prod_rec_five }}">{{ object.prod_rec_five|cut_string }}</a>
                        {% endif %}
                        {% if 'Survey' in object.hardware%}
                            <br>
                            <a href="{{ object.create_productionrecord_reversed }}">Get ProductionRecord</a>
                        {% endif %}
                        {% if object.prod_rec_string %}
                            {% for file in object.prod_rec_string|string_to_list %}
                                {% if file != 'None' %}
                                    {% if file != '' %}
                                        <a href="/media{{ file }}">{{ file|cut_string }}</a>
                                        <br>
                                    {% endif %}
                                {% endif  %}
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>{{ object.ordering_number }}</td>
                    <td><a class="own-btn" href="{{ object.get_comment_update_only }}">Edit</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div id="dialog" title="Error">
    <p>Dies ist ein älterer Eintrag der diese Funktion nicht unterstützt. <br> <i>This is an older entry that does not support this feature</i></p>
</div>
{% endblock %}
{% block script %}
<script>
setTimeout("document.location.reload();", 300000);
//setTimeout("document.location.reload();", 3000);

    $(function() {
        var thHeight = $("table#demo-table th:first").height();
        $("table#demo-table th").resizable({
          handles: "e",
          minHeight: thHeight,
          maxHeight: thHeight,
          minWidth: 40,
          resize: function (event, ui) {
            var sizerID = "#" + $(event.target).attr("id") + "-sizer";
            $(sizerID).width(ui.size.width);
          }
        });
    });

</script>
<script>
    $(document).ready(function() {
	    if($(window).width() < 500) {
	       window.close();
	    }
	    $("#demo-table").tablesorter();

        // if(navigator.userAgent.match(/Chrome/i)) {
		 //    $('#touch').show();
		 //    $('#clear').show();
        //
        //     $('#search').click(function() {
        //         var searchBox = $('input[type=text]').val();
        //         $("#demo-table .box-nr").each(function(){
        //             if ($(this).text().trim() == searchBox.toUpperCase()) {
        //                 $(this).show();
        //             } else {
        //                 $(this).parent().fadeOut();
        //             }
        //         });
        //     });
        // } else {
        //     $('#touch').hide();
        //     $('#clear').hide();
        // }

        $('#clear').click(function() {
            $("#demo-table .box-nr").each(function(){
                $(this).parent().show();
            });
        });
    });
</script>

<script>
    $(document).ready(function() {
        $(window).scrollTop();
        // $('#back-to-top').hide();
        // $(document).mousemove(function(e) {
        //     if ($(document).scrollTop() > 300) {
        //         $('#back-to-top').show();
        //     } else {
        //         $('#back-to-top').hide();
        //     }
        // });

        $('#back-to-top').click(function(){
            $("html, body").animate({ scrollTop: 0 }, 10);
            return false;
        });

        $('#refresh').click(function() {
            var auto = $('#refresh').html().trim();
            if (auto == 'off') {
                $('#refresh').html('on');
                window.location.href='#stop';
                window.location.href.reload();
            } else {
                $('#refresh').html('off');
                window.location.href = '#';
                setInterval(function() {
                  window.location.reload();
                }, 300000);
            }
      });
    });

    (function(){
        if (window.location.hash == '') {
            setInterval(function() {
                  window.location.href.reload();
                }, 300000);
        } else {
            $('#refresh').html('on');
            setInterval(function() {
                  alert('Autoreload ist aus');
                }, 300000);
        }
    }());
</script>
<script>

    function generateMarginToTopBtn() {
        var marginTop = $(window).height() - $('#back-to-top').offset().top - $('#back-to-top').height() - 20;
            $('#back-to-top').css('margin-top', marginTop.toString() + 'px');
        }

    $(document).ready(function () {

        generateMarginToTopBtn();

        var dialog = '#dialog';
        $(dialog).hide();

        if (window.location.href.indexOf('?') > 0) {

            window.setTimeout(activateScrolling, 2000);

            var location = window.location.href.split('?');
            if(location[1].trim() == 'error') {
                $(dialog).dialog();
                $(dialog).on('dialogclose', function(event) {
                    window.location.replace(location[0]);
                });
            }
            if (location[1].indexOf('obj') > -1) {
                var objLocation = location[1].split('=');
                jumpToObject(objLocation[1]);
            }

            function jumpToObject(progressNr) {
                var top = $(".box-nr p:contains("+ progressNr +")").offset().top;
                $("html, body").animate({ scrollTop: top - 300}, 10);

            }

            function activateScrolling() {
                $(document).scroll(function() {
                    var location = window.location.href.split('?');
                    history.pushState(null, null, location[0]);
                });
            }
        }

    });
</script>
{% endblock %}

prioListe/templates/assignment_done_update_form.html
{% extends 'base.html' %}
{% block title %}
    <title>Shipping Board</title>
{% endblock %}
{% block content %}
<div class="container" {%if  hardware_form %}
     style="margin-top:4%; margin-left:10%"
     {% else %} style="margin-top:4%"
     {% endif %}>
    <row>
        <h2>Update Vnr.: <b>{{ obj.ordering_number }}</b></h2>
        <h3>Customer: {{ obj.customer }}</h3>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table table-bordered">
                {% for field in form %}
                    {% if field.name == 'changed_by_ip' %}
                        <tr class="ip_addr">
                    {% else %}
                        <tr>
                    {% endif %}
                        {% if field.name == 'hardware' %}
                        <td><b>{{ field.label }}</b></td>
                        <td>
                            {% if hardware_form %}
                            <table>
                                <tr>
                                    {% for hform in hardware_form %}
                                        <td>{{ hform.as_p }}</td>
                                    {% endfor %}
                                </tr>
                            </table>
                            {% else %}
                                {{ field }}
                                {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            {% endif %}
                        </td>
                        {% else %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <td style="color:chocolate; font-size: 1.2em"><b>{{ error }}</b></td>
                                {% endfor %}
                            {% else %}
                                    <td><b>{{ field.label }}</b></td>
                            {% endif %}
                            <td>{{ field }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
            <div id="dialog" title="Error dialog">
            <h3 id="dialog-text"></h3>
        </div>
            <input class="btn btn-primary btn-lg btn-block submiter" type="submit" value="Bestätigen" onmouseover="checkform()">
        </form>
        <br>
        <a class="btn btn-warning btn-lg btn-block" href="{{ obj.get_delete_notice }}">Delete</a>
        <a class="btn btn-secondary btn-lg btn-block" href="{% url 'pListe:done' %}">Zurück</a>
    </row>
</div>
{% endblock %}

prioListe/templates/assignment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container" {%if  hardware_form %}
     style="margin-top:4%; margin-left:10%"
     {% else %} style="margin-top:4%"
     {% endif %}>
    <row>
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table table-bordered">
                {% for field in form %}
                    {% if field.name == 'changed_by_ip' %}
                        <tr class="ip_addr">
                    {% else %}
                        <tr>
                    {% endif %}
                        {% if field.name == 'hardware' %}
                        <td><b>{{ field.label }}</b></td>
                        <td>
                            {% if hardware_form %}
                            <table>
                                <tr>
                                    {% for hform in hardware_form %}
                                        <td>{{ hform.as_p }}</td>
                                    {% endfor %}
                                </tr>
                            </table>
                            {% else %}
                                {{ field }}
                                {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            {% endif %}
                        </td>
                        {% else %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <td style="color:chocolate; font-size: 1.2em"><b>{{ error }}</b></td>
                                {% endfor %}
                            {% else %}
                                    <td><b>{{ field.label }}</b></td>
                            {% endif %}
                            <td>{{ field }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
            <div id="dialog" title="Error dialog">
            <h3 id="dialog-text"></h3>
        </div>
            <input class="btn btn-primary btn-lg btn-block submiter" type="submit" value="Bestätigen" onmouseover="checkform()">
        </form>
        <br>
        <a class="btn btn-secondary btn-lg btn-block" href="{% url 'pListe:home' %}">Zurück</a>
    </row>
</div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $('.ip_addr').hide();
            var ip = false;
            window.RTCPeerConnection = window.RTCPeerConnection || window.mozRTCPeerConnection || window.webkitRTCPeerConnection || false;

            if (window.RTCPeerConnection) {
                ip = Array();
                var pc = new RTCPeerConnection({iceServers:[]}), noop = function(){};
                pc.createDataChannel('');
                pc.createOffer(pc.setLocalDescription.bind(pc), noop);

                pc.onicecandidate = function(event) {
                    if (event && event.candidate && event.candidate.candidate) {
                        var s = event.candidate.candidate.split('\n');
                        var ipString = s[0].split(' ')[4];
                        $('#id_changed_by_ip').val(ipString);
                        ip.push(s[0].split(' ')[4]);
                    }
                }
            }
        });

        function checkform(){
            if (window.location.href.indexOf('update') <= 0) {

                var regex = new RegExp("[A-Z]");

            $('.submiter').removeAttr('type');

            if ($('#id_form-0-number').val()) {
                $('#dialog').hide();
                $('.submiter').attr('type', 'submit');
            } else {
                $('#dialog').show();
                $('#dialog-text').text('Did you forget the Quantity??');
            }

            }
        }
    </script>
{% endblock %}

prioListe/templates/assignment_update_form.html
{% extends 'base.html' %}
{% block content %}
<div style="text-align:center; margin-top:10%;" class="container">
        <form action="#" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'production_remark' or field.name == 'hardware' %}
                        <div class="form-group textarea" align="right">
                            <label class="form-check-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                {% else %}
                        <div class="form-group" align="left">
                            <label class="form-check-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                {% endif %}
            {% endfor %}
        <input class="btn btn-primary btn-lg btn-block" type="submit" value="Bestätigen" >
        </form>
        <br>
        <a class="btn btn-secondary btn-lg btn-block" href="{% url 'pListe:home' %}">Zurück</a>
</div>
{% endblock %}
{% block script %}
    <script>
        document.getElementById("id_optional_status").onchange = function() {myFunction()};

        function myFunction() {
            var x = document.getElementById("id_status");
            x.value = '';
        }
    </script>
{% endblock %}

prioListe/templates/noticeAboutDelete.html
{% extends 'base.html' %}
{% block title %}
    <title>Shipping Board</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-sm-12 col-md-7 col-lg-7" style="margin-top: 10em;">
        <h2>Are you sure you want <b>DELETE</b> <i>{{ obj.ordering_number }}</i></h2>
        <form action="." method="post" class="form-group">
            {% csrf_token %}
            <h3><i>Kunde:</i> {{ obj.customer }} <br> <i>Hardware:</i> {{ obj.hardware|safe }}</h3>
            <input type="text" value="{{ object.pk }}" name="delete" id="id_delete"
                   style="display: none">
            <input type="submit" value="DELETE" class="btn btn-danger btn-block">
            <a href="{{ obj.get_comment_update_only }}" class="btn btn-success btn-block">Abbrechen</a>
        </form>
    </div>
</div>
{% endblock %}

prioListe/templates/update_shelf.html
{% include 'base.html' %}
{% block content %}
<div class="container">
    <div class="col-sm-12 col-md-6 col-lg-6" style="margin-top: 10em;">
        <h2>Update <b>{{ shelf_type|title }}fach</b></h2>
        <form action="." method="post" class="form-group">
            {% csrf_token %}
            <h3><i>Kiste</i>: {{ obj.box }} &emsp; <i>Kunde:</i> {{ obj.customer }} <br> <i>Hardware:</i> {{ obj.hardware|wordwrap:50|linebreaksbr }}</h3>
            <input type="text" value="{{ object.compartment }}" name="shelf" id="id_shelf"
                   style="margin-bottom: 0.5em; font-size: 21px!important;">
            <input type="submit" class="btn btn-primary btn-block">
            <a href="{{ obj.get_update_production }}" class="btn btn-danger btn-block">Abbrechen</a>
        </form>
    </div>
</div>
{% endblock %}