allSales/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from . import settings
from .views import MainView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^rma/', include('rma.urls', namespace='rma')),
    url(r'^prio/', include('prioListe.urls', namespace='pListe')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^statistic/', include('statistic.urls', namespace='statistic')),
    url(r'^warranty/', include('warranty.urls', namespace='warranty')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rma/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from allSales import settings
from . import views
from .views import RefurbishmentFormView
from .views import RefurbishmentUpdateView
from .views import RMADelete

app_name = 'rma'
urlpatterns = [
    url(r'^$', views.refurbishment_list, name='home'),
    url(r'^create/$', RefurbishmentFormView.as_view(), name='create'),
    url(r'^update/(?P<pk>[\d]+)$', RefurbishmentUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[\d+]+)$', RMADelete.as_view(), name='delete'),
    url(r'^search/$', views.search_customer, name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.conf.urls import url
from . import views
from . import utils
from .views import AllOrders
from .views import AllDoneOrders
from .views import SurveyDetailView
from .views import VertexLiteDetailView
from .views import MiniFawnDetailView
from .views import TrapTransmitterDetailView
from .views import SurveyUpdateView
from .views import VertexLiteUpdateView
from .views import MiniFawnUpdateView
from .views import TrapTransmitterUpdateView
from .views import SurveyPDFView
from .views import SurveyOriginPDFView
from .views import SurveyProductionRecord
from .views import VertexLiteProductionRecord
from .views import MiniFawnProductionRecord
from .views import TrapTransmitterProductionRecord
from .views import SurveyProductionRecordInitial
from .views import VertexLiteProductionRecordInitial
from .views import MiniFawnProductionRecordInitial
from .views import TrapTransmitterProductionRecordInitial
from .views import ProdRecPDFView
from .views import VtxlProdRecPDFView
from .views import MfProdRecPDFView
from .views import TrapTransProdRecPDFView
from .views import VertexLitePDFView
from .views import VertexLiteOriginPDFView
from .views import MiniFawnPDFView
from .views import MiniFawnOriginPDFView
from .views import TrapTransPDFView
from .views import TrapTransOriginPDFView
from .views import CreateSurveyPrioEntryByOrder
from .views import CreateVertexLitePrioEntryByOrder
from .views import CreateMiniFawnPrioEntryByOrder
from .views import CreateTrapTransmitterPrioEntryByOrder
from .views import ProdRecFromPrioListePDFView
from .views import SurveyModelDelete
from .views import VertexLiteModelDelete
from .views import MiniFawnModelDelete
from .views import TrapTransmitterModelDelete


app_name = 'sales'
urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^link/', views.create_link, name='createLink'),
    ############
    #Lists
    ############
    url(r'^list-open-orders/', AllOrders.as_view(), name='listsorders'),
    url(r'^list-done-orders/', AllDoneOrders.as_view(), name='listdoneorders'),
    ############
    #Detail View
    ############
    url(r'^detail-surveys/(?P<pk>[\d]+)/$', SurveyDetailView.as_view(), name='detailsurveys'),
    url(r'^detail-vertex-lite/(?P<pk>[\d]+)/$', VertexLiteDetailView.as_view(), name='detailvertexlite'),
    url(r'^detail-mini_fawn/(?P<pk>[\d]+)/$', MiniFawnDetailView.as_view(), name='detailminifawn'),
    url(r'^detail-trap_trans/(?P<pk>[\d]+)/$', TrapTransmitterDetailView.as_view(), name='detailtraptrans'),
    ############
    #Update View
    ############
    url(r'^update-surveys/(?P<pk>[\d]+)/$', SurveyUpdateView.as_view(), name='updatesurveys'),
    url(r'^update-vertex-lite/(?P<pk>[\d]+)/$', VertexLiteUpdateView.as_view(), name='updatevertexlite'),
    url(r'^update-mini-fawn/(?P<pk>[\d]+)/$', MiniFawnUpdateView.as_view(), name='updateminifawn'),
    url(r'^update-trap-trans/(?P<pk>[\d]+)/$', TrapTransmitterUpdateView.as_view(), name='updatetraptrans'),
    ############
    #Instant Accept
    ############
    url(r'^accept-survey/(?P<pk>[\d]+)/$', views.accept_survey_order, name='acceptsurvey'),
    url(r'^accept-vertex-lite/(?P<pk>[\d]+)/$', views.accept_vertex_lite_order, name='acceptvertexlite'),
    url(r'^accept-mini-fawn/(?P<pk>[\d]+)/$', views.accept_mini_fawn_order, name='acceptminifawn'),
    url(r'^accept-trap-trans/(?P<pk>[\d]+)/$', views.accept_trap_transmitter_order, name='accepttraptrans'),
    ############
    #Write into prioList
    ############
    url(r'^accept-survey-write-prioliste/(?P<pk>[\d]+)/$', CreateSurveyPrioEntryByOrder.as_view(),
        name='acceptsurveywriteprioliste'),
    url(r'^accept-vtxl-write-prioliste/(?P<pk>[\d]+)/$', CreateVertexLitePrioEntryByOrder.as_view(),
        name='acceptvertexlitewriteprioliste'),
    url(r'^accept-mf-write-prioliste/(?P<pk>[\d]+)/$', CreateMiniFawnPrioEntryByOrder.as_view(),
        name='acceptminifawnwriteprioliste'),
    url(r'^accept-tt-write-prioliste/(?P<pk>[\d]+)/$', CreateTrapTransmitterPrioEntryByOrder.as_view(),
        name='accepttraptranswriteprioliste'),
    ############
    #Pdf File
    ############
    url(r'^surveys-order-pdf/(?P<pk>[\d]+)/$', SurveyPDFView.as_view(), name='surveyorderpdf'),
    url(r'^surveys-origin-pdf/(?P<pk>[\d]+)/$', SurveyOriginPDFView.as_view(), name='surveyoriginpdf'),
    url(r'^vertex-lite-order-pdf/(?P<pk>[\d]+)/$', VertexLitePDFView.as_view(), name='vertexliteorderpdf'),
    url(r'^vertex-lite-origin-pdf/(?P<pk>[\d]+)/$', VertexLiteOriginPDFView.as_view(), name='vertexliteoriginpdf'),
    url(r'^mini-fawn-order-pdf/(?P<pk>[\d]+)/$', MiniFawnPDFView.as_view(), name='minifawnorderpdf'),
    url(r'^mini-fawn-origin-pdf/(?P<pk>[\d]+)/$', MiniFawnOriginPDFView.as_view(), name='minifawnoriginpdf'),
    url(r'^trap-trans-order-pdf/(?P<pk>[\d]+)/$', TrapTransPDFView.as_view(), name='traptransorderpdf'),
    url(r'^trap-trans-origin-pdf/(?P<pk>[\d]+)/$', TrapTransOriginPDFView.as_view(), name='traptransoriginpdf'),
    ############
    #ProdRecordsPdf
    ############
    url(r'^prod-rec-survey-pdf/(?P<pk>[\d]+)/$', ProdRecPDFView.as_view(), name='prodrecpdf'),
    url(r'^prod-rec-vtxl-pdf/(?P<pk>[\d]+)/$', VtxlProdRecPDFView.as_view(), name='vtxlprodrecpdf'),
    url(r'^prod-rec-minf-pdf/(?P<pk>[\d]+)/$', MfProdRecPDFView.as_view(), name='mfprodrecpdf'),
    url(r'^prod-rec-ttr-pdf/(?P<pk>[\d]+)/$', TrapTransProdRecPDFView.as_view(), name='traptransprodrecpdf'),
    url(r'^prod-rec-pdf/(?P<pk>[\d]+)/(?P<progress_number>[\d]+)/$', ProdRecFromPrioListePDFView.as_view(),
        name='prodrecpdf_fromprioliste'),
    url(r'^print-prod-rec-pdf/(?P<pk>[\d]+)/$', utils.prod_rec_print, name='printprodrecpdf'),
    ############
    #Search and filter views
    ############
    url(r'^search/(?P<redirect_url>.*)/$', views.search, name='search'),
    ############
    #ProdRecords
    ############
    url(r'^survey-prod-rec/(?P<pk>[\d]+)/$', SurveyProductionRecord.as_view(), name='prodrec'),
    url(r'^vl-prod-rec/(?P<pk>[\d]+)/$', VertexLiteProductionRecord.as_view(), name='vlprodrec'),
    url(r'^mf-prod-rec/(?P<pk>[\d]+)/$', MiniFawnProductionRecord.as_view(), name='mfprodrec'),
    url(r'^tt-prod-rec/(?P<pk>[\d]+)/$', TrapTransmitterProductionRecord.as_view(), name='ttprodrec'),
    url(r'^initial-survey-prod-rec/(?P<pk>[\d]+)/$', SurveyProductionRecordInitial.as_view(), name='initialprodrec'),
    url(r'^initial-vtxl-prod-rec/(?P<pk>[\d]+)/$', VertexLiteProductionRecordInitial.as_view(), name='vtxlinitialprodrec'),
    url(r'^initial-mf-prod-rec/(?P<pk>[\d]+)/$', MiniFawnProductionRecordInitial.as_view(), name='mfinitialprodrec'),
    url(r'^initial-tt-prod-rec/(?P<pk>[\d]+)/$', TrapTransmitterProductionRecordInitial.as_view(), name='ttinitialprodrec'),
    url(r'^prod-rec-update/(?P<pk>[\d]+)/$', views.survey_production_record_update, name='updateprodrec'),
    url(r'^prod-rec-update/(?P<pk>[\d]+)/$', views.vertex_lite_production_record_update, name='updateprodrecvtxl'),
    url(r'^prod-rec-update/(?P<pk>[\d]+)/$', views.mini_fawn_production_record_update, name='updateprodrecmf'),
    url(r'^prod-rec-update/(?P<pk>[\d]+)/$', views.trap_trans_production_record_update, name='updateprodrectraptrans'),
    ############
    #Delete View
    ############
    url(r'^delete/(?P<pk>[\d]+)/$', SurveyModelDelete.as_view(), name='surveydelete'),
    url(r'^delete/(?P<pk>[\d]+)/$', VertexLiteModelDelete.as_view(), name='vertexlitedelete'),
    url(r'^delete/(?P<pk>[\d]+)/$', MiniFawnModelDelete.as_view(), name='minifawndelete'),
    url(r'^delete/(?P<pk>[\d]+)/$', TrapTransmitterModelDelete.as_view(), name='traptransdelete'),
]

sales/models.py
import datetime
from django.conf import settings
from django.db import models
from django.urls import reverse

DEFAULTBELTSHAPES = ['round-shaped', 'drop-shaped']
BELTTHICKNESSES = ['3.4 mm (SF/SF)', '4.2 mm (ST/SF)', '5 mm (ST/ST)']
DEFAULTEDGES = ['round', 'smooth']
DEFAULTCOLORS = ['black', 'white', 'tan', 'brown', 'yellow', 'other']
DEFAULTWIDTH = ['25 mm', '32 mm', '38 mm', '50 mm', '63 mm', '75 mm']

BELTSHAPES = ((shape, shape) for shape in DEFAULTBELTSHAPES)

BELTWIDTH = ((width, width) for width in DEFAULTWIDTH)

BELTTHICKNESS = ((thickness, thickness) for thickness in BELTTHICKNESSES)

BELTEDGES = ((edge, edge) for edge in DEFAULTEDGES)

BELTCOLORS = ((color, color) for color in DEFAULTCOLORS)

PAYMENTOPTIONS = (
    ('Purchase with Order No.', 'Purchase with Order No.'),
    ('Bank Wire Transfer', 'Bank Wire Transfer'),
    ('Check', 'Check'),
    ('Credit Card', 'Credit Card (3.0% service fee)'),
)

UTCORLMT = (
    ('utc', 'UTC'),
    ('lmt', 'LMT')
)


def upload_path(instance, filename):
    return '/'.join([settings.MEDIA_ROOT, str(instance.contacts_faktura_id), filename])


def gps_schedule_upload_path(instance, filename):
    return '/'.join([settings.MEDIA_ROOT, str(instance.contacts_faktura_id), 'gps_schedule', filename])


def vhf_schedule_upload_path(instance, filename):
    return '/'.join([settings.MEDIA_ROOT, str(instance.contacts_faktura_id), 'vhf_schedule', filename])


class LinkHash(models.Model):
    class Meta:
        db_table = 'hash'
        app_label = 'sales'
        managed = False

    hash = models.TextField(max_length=255)

    def get_main_root(self):
        return reverse('sales:overview')

    def get_labelname(self):
        return 'To Orderings'


class ProductionRecordInputMiniGL(models.Model):
    co_worker = models.CharField(max_length=100, blank=True, null=True)
    animal_species = models.CharField(max_length=255, blank=True, null=True)
    gps_schedule_name = models.CharField(max_length=255, blank=True, null=True)
    vhf_schedule_name = models.CharField(max_length=255, blank=True, null=True)
    gl_no_of_attempts = models.IntegerField(blank=True, null=True)
    gl_fixes_per_message = models.IntegerField(blank=True, null=True)
    further_instructions_programming = models.TextField(max_length=500, blank=True, null=True)
    path_customer_folder = models.CharField(max_length=500, blank=True, null=True)

    class Meta:
        abstract = True


class ProductionRecordInput(ProductionRecordInputMiniGL):
    punching1_dist = models.CharField(max_length=50, default='')
    punching1_pos = models.IntegerField()
    punching1_neg = models.IntegerField()
    punching2 = models.CharField(max_length=50)
    further_instructions_belt = models.TextField(max_length=500, blank=True, null=True)
    ir_contract_type = models.CharField(max_length=255, blank=True, null=True)
    ir_fixes_per_message = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True


class MiniBaseModel(models.Model):

    class Meta:
        abstract = True

    payment_option = models.CharField(choices=PAYMENTOPTIONS, max_length=255, blank=True, default='check')
    order_no = models.CharField(null=True, blank=True, max_length=255)
    as_post = models.BooleanField(default=False, blank=True)
    as_email = models.BooleanField(default=True, blank=True)
    invoice_mail = models.EmailField(null=True, blank=True)
    number_of_collars = models.CharField(null=True, blank=True, max_length=100)
    customer_faktura_id = models.IntegerField(editable=False, null=True)
    contacts_faktura_id = models.IntegerField(null=True, blank=True)
    same_addr = models.BooleanField(blank=True, default=True)
    globalstar = models.BooleanField(blank=True, default=False)
    iridium = models.BooleanField(blank=True, default=False)
    vhf_beacon_schedule = models.CharField(blank=True, default='24', max_length=255, null=True)
    vhf_beacon_frequency = models.TextField(blank=True, null=True, default=148)
    contact_name_airtime_fee = models.CharField(blank=True, null=True, max_length=255)
    contact_mail_airtime_fee = models.EmailField(blank=True, null=True)
    notification_mail = models.CharField(blank=True, null=True, max_length=500)
    notification_sms = models.CharField(blank=True, null=True, max_length=255)

    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now())
    customer_staff = models.CharField(blank=True, null=True, max_length=255)
    origin = models.TextField(editable=False, null=True, blank=True, max_length=1000)
    order_acceptet = models.BooleanField(default=False)
    operation_number = models.CharField(db_column='operation_Number', max_length=255, blank=True, null=True)
    id_tag = models.BooleanField(blank=True, default=False)
    airtime_contract = models.FileField(blank=True, upload_to=upload_path, null=True)
    vat_ein_number = models.CharField(max_length=255, blank=True, null=True, default='')
    delivery_time = models.DateField(blank=True, null=True)
    inc_or_gmbh = models.CharField(blank=True, null=True, default='gmbh', max_length=13)
    owm_gps_schedule = models.FileField(null=True, blank=True, upload_to=gps_schedule_upload_path)
    own_vhf_schedule = models.FileField(null=True, blank=True, upload_to=vhf_schedule_upload_path)


class BaseModelWithoutBeltDesign(MiniBaseModel):

    class Meta:
        abstract = True

    animal_species = models.CharField(max_length=255, blank=True, null=True)
    battery_size = models.CharField(max_length=100, null=True, blank=True)
    nom_collar_circumference = models.TextField(blank=True, null=True, max_length=255)
    mortality_sensor = models.PositiveIntegerField(blank=True, null=True, default=24)
    utc_lmt = models.CharField(blank=True, default=False, max_length=50, choices=UTCORLMT, null=True)
    utc_correction = models.DecimalField(blank=True, null=True, max_digits=4, decimal_places=2)
    cotton_layers = models.IntegerField(blank=True, null=True)

    gps_schedule = models.CharField(blank=True, default='Every 13h', max_length=255, null=True)
    iridium_num_of_fixes_gps = models.IntegerField(blank=True, null=True)
    iridium_contract_type = models.CharField(max_length=255, null=True, blank=True, default='')


class BaseModel(BaseModelWithoutBeltDesign):

    belt_width = models.CharField(choices=BELTWIDTH, blank=True, null=True, max_length=255)
    belt_thickness = models.CharField(choices=BELTTHICKNESS, blank=True, null=True, max_length=255)
    belt_edge = models.CharField(choices=BELTEDGES, blank=True, null=True, max_length=255, default='round')
    belt_colour = models.CharField(choices=BELTCOLORS, blank=True, null=True, max_length=255)
    other_color = models.CharField(max_length=100, blank=True, null=True)
    belt_labeling = models.BooleanField(blank=True, default=False)
    belt_labeling_instructions = models.CharField(max_length=255, null=True, blank=True)
    belt_plates = models.BooleanField(blank=True, default=False)
    belt_plates_instructions = models.CharField(max_length=76, null=True, blank=True)
    belt_shape = models.CharField(choices=BELTSHAPES, max_length=255, blank=True, null=True)

    reflective_stripes = models.BooleanField(blank=True, default=False)
    reflective_stripes_instructions = models.CharField(max_length=76, null=True, blank=True)

    class Meta:
        abstract = True

sales/templates/action_buton.html
<a href="{{ object.get_back_to_list }}" class="btn btn-secondary open-list-btn">Back to list</a>
<a href="{% url 'sales:listdoneorders' %}" class="btn btn-secondary done-list-btn" style="display: none">Back to list</a>
<a href="{{ object.get_sells_update_url }}" class="btn btn-success edit-btn">Edit</a>
<a href="{{ object.get_pdf }}" class="btn btn-info">
{% if object.order_acceptet %}
    Order Pdf
{% else %}
    Draft Pdf
{% endif %}
</a>
<a href="{{ object.get_prod_rec_pdf }}" class="btn btn-info">Pre Production Record</a>
<div style="float:right">

{% if not inPrioListe %}
    {% if object.check_for_prod_rec %}
        <a href="{{ object.get_accept_url }}"
       target="_blank"
       onClick="window.open('{{ object.write_into_priolist }}','pagename', 'resizable,height=900,width=450,left=' + (parseInt(window.innerWidth) * 0.85) + ',top=100'); return false;"
       class="btn btn-secondary accept-order-btn btn-danger">Accept Survey Order and write into PrioListe</a>
    {% endif %}
{% endif %}
</div>

sales/templates/basePdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Form</title>
    <link rel="icon" href="https://www.vectronic-aerospace.com/wp-content/uploads/2016/04/logo180.gif">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js" integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css">

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css">

    {% block extra_style %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}
</body>
</html>

sales/templates/collar_programming_template.html
<table class="table" style="border: 1px solid black;">
    <tr>
        <td class="main-td">Mortality sensor delay time: <b>
            {% if object.mortality_sensor %}
                {{ object.mortality_sensor }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
        <td class="main-td"></td>
    </tr>
    <tr>
        <td class="main-td">Notification e-mail: <b>
            {% if object.notification_mail %}
                {{ object.notification_mail }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
        <td class="main-td">Notification SMS: <b>
            {% if object.notification_sms %}
                {{ object.notification_sms }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
    </tr>
    <tr>
        <td class="main-td">Timezone: <b>
            {% if object.utc_lmt %}
                {{ object.utc_lmt|upper }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
        <td class="main-td">UTC correction: <b>
            {% if object.utc_correction %}
                {{ object.utc_correction }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
    </tr>
    <tr>
        <td class="main-td">GPS schedule: <b>
            {% if object.gps_schedule %}
                {{ object.gps_schedule|upper }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
        <td class="main-td">VHF beacon schedule: <b>
            {% if object.vhf_beacon_schedule %}
                {{ object.vhf_beacon_schedule }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
    </tr>
    <tr>
        <td class="main-td">Uploaded an GPS schedule: <b>
            {% if object.owm_gps_schedule %}
                true
            {% else %}
                false
            {% endif %}
        </b></td>
        <td class="main-td">Uploaded an VHF beacon schedule: <b>
            {% if object.own_vhf_schedule %}
                true
            {% else %}
                false
            {% endif %}
        </b></td>
    </tr>
    <tr>
        <td class="main-td">ID-Tag: <b>
            {% if object.id_tag %}
                {{ object.id_tag }}
            {% else %}
                not specified
            {% endif %}
        </b></td>
        <td class="main-td"></td>
    </tr>
</table>

sales/templates/list_of_collars.html
{% extends 'sales_base.html'%}
{% load extra_tags %}
{% block extra_style %}
<style>
    @media screen and (max-width: 940px) {
        .diff-shipping {
            display: none!important;
        }
    }
</style>
{% endblock %}
{% block content %}
    <div class="col-md-12 col-lg-12">
        <h1 style="margin-left: 35%">{{ title }}</h1>
        <div class="col-md-12 col-lg-12">
            <div class="col-sm-12 col-md-4 col-lg-4">
                <form action="{% url 'sales:search' title|replace_whitespace:'' %}" method="post" style="float:left; display: inline-grid;">
                    {% csrf_token %}
                    {{ form_search.as_p }}
                <input type="submit" value="Search/Clear" class="btn btn-dark btn-sm">
            </form>
            </div>
            <div class="col-sm-12 col-md-offset-4 col-lg-offset-4 col-md-3 col-lg-3" style="float:right">
                <a href="{% url 'sales:overview'  %}" class="btn btn-secondary btn-sm">Back to overview</a>
                {% if 'Accepted' in title %}
                    <a href="{% url 'sales:listsorders'  %}" class="btn btn-info btn-sm">To running orders</a>
                {% else %}
                    <a href="{% url 'sales:listdoneorders'  %}" class="btn btn-info btn-sm">To accepted orders</a>
                {% endif %}
                    <a href="{% url 'pListe:home'  %}" class="btn btn-primary btn-sm">To Priority-List</a>
            </div>
        </div>
        <row>
            <table class="table tablesorter">
                <thead>
                    <tr>
                        <th>Operation Number</th>
                        <th>Customer Staff</th>
                        <th>Internal Staff</th>
                        <th>Created at</th>
                        <th>Contact Name</th>
                        <th>Customer No.</th>
                        <th>Collartype</th>
                        <th>Customer Input</th>
                        <th>Order Pdf</th>
                        <th>Pre Production Record</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for element in list_objects %}
                        {% for object in element %}
                            {% if object.customer_invoice_address %}
                                <tr style="background-color:#ffcc66">
                            {% else %}
                                <tr style="background-color:#ff6666;">
                            {% endif %}
                            {% if object.order_acceptet %}
                                <tr style="background-color:#beeabe;">
                            {% endif %}
                                {% if object.operation_Number %}
                                    <td> {{ object.operation_Number }}</td>
                                {% else %}
                                    <td> {{ object.operation_number }}</td>
                                {% endif %}
                                <td> {{ object.customer_staff }}</td>
                                <td> {{ object.get_co_worker }}</td>
                                <td> {{ object.created_at|date:"SHORT_DATE_FORMAT" }} </td>
                                <td> {{ object.customer_invoice_address.contact_person }}</td>
                                <td> {{ object.contacts_faktura_id }}</td>
                                <td> {{ object.get_model_type }} </td>
                                <td> <a href="{{ object.get_origin_pdf }}">original.pdf</a> </td>
                                <td> <a href="{{ object.get_pdf }}">order.pdf</a> </td>
                                <td> <a href="{{ object.get_prod_rec_pdf }}">Pre_Prod_Record.pdf</a></td>
                                <td> <a href="{{ object.get_sells_detail_url }}">Edit</a></td>
                                <td> <a href="{{ object.get_delete_url }}" class="btn-warning">[ X ]</a></td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
        </table>
        </row>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function() {
            $('.table').tablesorter( {sortList: [[0,0], [1,0]]} );
        });
    </script>
{% endblock %}

sales/templates/overview.html
{% extends 'sales_base.html' %}
{% block content %}
<div class="col-md-12 col-lg-12">
    <h1 style="margin-left: 35%">Overview</h1>
    <div class="col-md-offset-3 col-md-3 col-lg-offset-4 col-lg-3">
        <table class="table">
            <tr>
                <td><h3><a href="{% url 'sales:createLink' %}" style="color:green!important">Generate Link</a></h3></td>
            </tr>
            <tr>
                <td><h3><a href="{% url 'sales:listsorders' %}" style="color:#ffc107!important">Overview running Orders</a></h3></td>
            </tr>
            <tr>
                <td><h3><a href="{% url 'sales:listdoneorders' %}" style="color:chocolate!important">Overview acceptet Orders</a></h3></td>
            </tr>
            <tr>
                <td><h3><a href="{% url 'main' %}">Back to Main-Page</a></h3></td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}