allSales/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from . import settings
from .views import MainView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^rma/', include('rma.urls', namespace='rma')),
    url(r'^prio/', include('prioListe.urls', namespace='pListe')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^statistic/', include('statistic.urls', namespace='statistic')),
    url(r'^warranty/', include('warranty.urls', namespace='warranty')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rma/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from allSales import settings
from . import views
from .views import RefurbishmentFormView
from .views import RefurbishmentUpdateView
from .views import RMADelete

app_name = 'rma'
urlpatterns = [
    url(r'^$', views.refurbishment_list, name='home'),
    url(r'^create/$', RefurbishmentFormView.as_view(), name='create'),
    url(r'^update/(?P<pk>[\d]+)$', RefurbishmentUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[\d+]+)$', RMADelete.as_view(), name='delete'),
    url(r'^search/$', views.search_customer, name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rma/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse

from collar.models import Staff

CHOICES = [
    ('', ''),
]
for staff in Staff.objects.all():
    CHOICES.append((staff.name, staff.name))


def file_upload_path(instance, filename):
    return '/'.join(['media', instance.salesPerson, filename])


class Status(models.Model):
    name = models.TextField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'status'
        app_label = 'rma'


class RMAFile(models.Model):
    rma_file = models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')

    class Meta:
        db_table = 'rmafiles'
        app_label = 'rma'


class Refurbisment(models.Model):
    rma = models.TextField(max_length=200)
    salesPerson = models.CharField(max_length=100, choices=CHOICES)
    customer_forename = models.TextField(max_length=200, default='Forename')
    customer_name = models.TextField(max_length=200, default='Surname')
    customer_email = models.EmailField()
    country = models.TextField(max_length=200)
    content = models.TextField(max_length=750, null=True, blank=True)
    parcel_received = models.DateField(blank=True, default=datetime.strptime('2000-01-01', '%Y-%m-%d'))
    comments = models.TextField(max_length=750, null=True, blank=True)
    status = models.ForeignKey(to=Status)
    rma_file = models.FileField(null=True, blank=True, upload_to=file_upload_path)
    rma_second_file = models.FileField(null=True, blank=True, upload_to=file_upload_path)
    shelf = models.PositiveIntegerField(null=True, blank=True)
    #more_files = models.CharField(null=True, blank=True, max_length=255)

    def get_update_url(self):
        return reverse('rma:update',
                       kwargs={'pk': self.pk})

    def get_main_root(self):
        return reverse('rma:home')

    def get_labelname(self):
        return 'To RMA-List'

    def get_delete_url(self):
        return reverse('rma:delete', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'refurbisment'
        ordering = ['status']
        app_label = 'rma'

rma/forms.py
from django import forms
from django.forms import Textarea

from .models import Refurbisment
from django.utils.timezone import now

class RefursbishmentForm(forms.ModelForm):
    class Meta:
        model = Refurbisment
        fields = '__all__'
        widgets = {
            'rma': Textarea(attrs={'cols': 20, 'rows': 2}),
            'customer_forename': Textarea(attrs={'cols': 20, 'rows': 2}),
            'customer_name': Textarea(attrs={'cols': 20, 'rows': 2}),
            'country': Textarea(attrs={'cols': 20, 'rows': 2}),
            'content': Textarea(attrs={'cols': 30, 'rows': 10}),
            'comments': Textarea(attrs={'cols': 30, 'rows': 10}),
            'rma_file': forms.ClearableFileInput(attrs={'multiple': True}),
            'shelf': forms.NumberInput(attrs={'min': '0', 'max': '30', 'step': '1'})
        }


class RefursbishmentUpdateForm(forms.ModelForm):
    class Meta:
        model = Refurbisment
        fields = '__all__'
        widgets = {
            'rma': Textarea(attrs={'cols': 20, 'rows': 2}),
            'customer_forename': Textarea(attrs={'cols': 20, 'rows': 2}),
            'customer_name': Textarea(attrs={'cols': 20, 'rows': 2}),
            'country': Textarea(attrs={'cols': 20, 'rows': 2}),
            'content': Textarea(attrs={'cols': 30, 'rows': 10}),
            'comments': Textarea(attrs={'cols': 30, 'rows': 10}),
            'rma_file': forms.ClearableFileInput(attrs={'multiple': True}),
            'more_files': forms.Textarea(attrs={'cols': 20, 'rows': 2, 'readonly': 'readonly'}),
            'shelf': forms.NumberInput(attrs={'min': '0', 'max': '30', 'step': '1'})
        }


class RMASearchForm(forms.Form):
    search = forms.CharField(label='Search', required=False)

rma/views.py
from django.shortcuts import render, redirect
from django.utils.timezone import now
from datetime import datetime
# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, DeleteView
from django.views.generic import CreateView

from prioListe.utils import searching
from .forms import RefursbishmentForm
from .forms import RefursbishmentUpdateForm
from .forms import RMASearchForm
from .models import Refurbisment
import os


def handle_uploaded_files(f, filepath, filename):
    try:
        with open('media/' + filepath + filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
    except FileNotFoundError:
        os.mkdir('media/' + filepath)
        handle_uploaded_files(f, filepath, filename)


def get_files(request, file_liste, clear=''):
    clear = request.POST.get('rma_file-clear')
    salesPerson = request.POST.get('salesPerson')
    for file in request.FILES.getlist('rma_file'):
        try:
            handle_uploaded_files(file, 'media/' + salesPerson + '/', str(file))
        except:
            pass
        file_liste.append(str(file))


class RefurbishmentFormView(CreateView):
    form_class = RefursbishmentForm
    template_name = 'rma_form.html'
    file_liste = []

    def get_success_url(self):
        return reverse('rma:home')

    def form_valid(self, form):
        return super(RefurbishmentFormView, self).form_valid(form)


class RefurbishmentUpdateView(UpdateView):
    model = Refurbisment
    form_class = RefursbishmentUpdateForm
    template_name = 'rma_form.html'
    file_liste = []
    clear = None

    def get_success_url(self):
        return reverse('rma:home')
    
    def form_valid(self, form):
        return super(RefurbishmentUpdateView, self).form_valid(form)

    def get_initial(self):
        initial = super(RefurbishmentUpdateView, self).get_initial()
        if str(self.object.parcel_received) == '2000-01-01':
            initial['parcel_received'] = now()
        else:
            initial['parcel_received'] = self.object.parcel_received
        return initial


def refurbishment_list(request):
    object_list = Refurbisment.objects.all().exclude(status__name='Out in Production for Refurbishment')
    return rma_main_list(request, object_list)


def search_customer(request):
    if request.method == 'POST':
        form = RMASearchForm(request.POST)
        if form.is_valid():
            search_string = form['search'].value()
            if search_string == '':
                return redirect(reverse('rma:home'))
            else:
                t = searching(Refurbisment, search_string)
                liste = Refurbisment.objects.none()
                for i in t:
                    liste = i | liste  # merge Querysets

            return rma_main_list(request, liste)
        else:
            return redirect(reverse('rma:home'))
    else:
        return redirect(reverse('rma:home'))


def rma_main_list(request, object_list):
    context = {
        'object_list': object_list,
        'search_form': RMASearchForm,
    }
    return render(request, template_name='rma_list.html', context=context)


class RMADelete(DeleteView):
    model = Refurbisment
    template_name = 'rma_notice_delete.html'
    success_url = reverse_lazy('rma:home')

rma/templates/rma_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RMA List</title>
    <link rel="icon" href="http://dev.vectronic-aerospace.com/wp-content/uploads/2016/04/logo180.gif">
    <script src="/static/js/tablesorter/jquery-latest.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js" integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css">

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css">
    <script src="/static/js/tablesorter/jquery.tablesorter.js"></script>

    <style>
        .textareas {
            margin-top: -13%;
        }
        .img-check {
            max-width: 7.8%;
        }
        .img-leer {
            width: 7.5%;
        }
        .own-btn {

        }
        .img-hidden {
            max-width: 7.8%;
        }
    </style>
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}
</body>
</html>

rma/templates/rma_form.html
{% extends 'rma_base.html' %}
{% load i18n %}
{% block content %}
<div class="container" style="margin-top:4%">
    <row>
        <form method="post" action="" class="row" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                {% if field.id_for_label != id_parcel_received %}
                    <div class="col-5">
                {% else %}
                    <div style="margin-left:37%" >
                {% endif %}
                    <label style="display:block">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary btn-lg btn-block" style="margin-top:2%">
            <a href="{% url 'rma:home'%}" class="btn btn-secondary btn-lg btn-block">Back</a>
        </form>
    </row>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $('#id_parcel_received').datepicker({
            dateFormat: 'yy-mm-dd',
        });
        //$('#id_parcel_received').datepicker().datepicker('setDate', new Date());
    });

    $(function() {
        $('#id_parcel_received').datepicker({
            dateFormat: 'yy-mm-dd',
        });
    });
</script>
{% endblock %}

rma/templates/rma_list.html
{% extends 'rma_base.html' %}
{% load i18n %}
{% load extra_tags %}
{% block content %}
    <div class="container-fluid">
        <p><a href="{% url 'rma:create' %}" class="btn btn-default">Neuen Eintrag erstellen</a>
            <span>Autoreload: </span><button id="refresh" class="btn btn-primary" >off</button>
            <span><a href="{% url 'main' %}" class="btn btn-info btn-sm" style="float:right">Back to Main-Page</a></span>
            <form action="{% url 'rma:search' %}" method="post" style="float:left; display: inline-grid;">
                {% csrf_token %}
                {{ search_form.as_p }}
                <input type="submit" value="Search/Clear" class="btn btn-dark btn-sm">
            </form>
        </p>
        <div class="col-md-offset-11 col-lg-offset-11 col-md-1 col-lg-1" style="z-index: 2">
            <button id="back-to-top" class="btn btn-info" style="position: fixed; margin-top:30%;">To Top</button>
        </div>
        <table id="demo-table" class="table table-bordered tablesorter">
            <thead>
                <tr>
                    <th>RMA#</th>
                    <th>Contact Person</th>
                    <th>Customer</th>
                    <th>Email</th>
                    <th>Country</th>
                    <th>Content</th>
                    <th>Shelf</th>
                    <th>File</th>
                    <th>Parcel Received</th>
                    <th>Status</th>
                    <th>Comments</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                {% if object.status|stringformat:"s" == "Storage" %}
                    <tr style="background-color:#FFFF00">
                {% elif object.status|stringformat:"s" == "On the way" %}
                    <tr style="background-color:#c8fdc8">
                {% elif object.status|stringformat:"s" == "Contact Customer" %}
                    <tr style="background-color:#D3D3D3">
                {% elif object.status|stringformat:"s" == "Responsible Sales Person" %}
                    <tr style="background-color:deepskyblue">
                {% elif object.status|stringformat:"s" == "Customer confirmation missing" %}
                    <tr style="background-color:#ffccff">
                {% elif object.status|stringformat:"s" == "" %}
                    <tr>
                {% else %}
                     <tr style="background-color:#BFF2FF">
                {% endif %}
                    <td>{{ object.rma|wordwrap:20|linebreaksbr }}</td>
                    <td>{{ object.salesPerson|wordwrap:20|linebreaksbr }}</td>
                    <td>{{ object.customer_forename }} / {{ object.customer_name }}</td>
                    <td><a href="mailto:{{ object.customer_email }}?subject={{ object.rma }}">{{ object.customer_email|wordwrap:30|linebreaksbr }}</a></td>
                    <td>{{ object.country|wordwrap:30|linebreaksbr }}</td>
                    <td>{{ object.content|tmp:','|safe }}</td>
                    {% if object.shelf %}
                        <td>{{ object.shelf }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td>{% if object.rma_file %}
                            <a href="/media/{{ object.rma_file }}">X</a>
                        {% endif %}
                        {% if object.rma_second_file %}
                            <a href="/media/{{ object.rma_second_file }}">X</a>
                        {% endif %}
                    </td>
                    <td>{{ object.parcel_received|date:'Y-m-d' }}</td>
                    <td>{{ object.status|wordwrap:2|linebreaksbr }}</td>
                    <td>{{ object.comments|wordwrap:40|linebreaksbr }}</td>
                    <td><a class="own-btn" href="{{ object.get_update_url }}">Edit</a></td>
                    <td><a class="own-btn btn-danger" href="{{ object.get_delete_url }}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function() {
        setTimeout("document.location.reload();", 300000);
        $("#demo-table").tablesorter();

    });
</script>

<script>
    $(document).ready(function() {

        $('#back-to-top').hide();
        $(document).mousemove(function(e) {
            if ($(document).scrollTop() > 300) {
                $('#back-to-top').show();
            } else {
                $('#back-to-top').hide();
            }
        });

        $('#back-to-top').click(function(){
            $("html, body").animate({ scrollTop: 0 }, 10);
            return false;
        });

        $('#refresh').click(function() {
            var auto = $('#refresh').html().trim();
            if (auto == 'off') {
                $('#refresh').html('on');
                window.location.href='#stop';
                window.location.href.reload();
            } else {
                $('#refresh').html('off');
                window.location.href = '#';
                setInterval(function() {
                  window.location.href.reload();
                }, 300000);
            }
      });
    });

    (function(){
        if (window.location.hash == '') {
            setInterval(function() {
                  window.location.href.reload();
                }, 300000);
        } else {
            $('#refresh').html('on');
            setInterval(function() {
                  alert('Autoreload ist aus');
                }, 300000);
        }
    }());
</script>
{% endblock %}

rma/templates/rma_notice_delete.html
{% extends 'rma_base.html' %}
{% block title %}
    <title>RMA</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-sm-12 col-md-7 col-lg-7" style="margin-top: 10em;">
        <h2>Are you sure you want <b>DELETE</b> <i>{{ object.ordering_number }}</i></h2>
        <form method="post" class="form-group">
            {% csrf_token %}
            <h3><i>Kunde:</i> {{ object.customer_forename }} {{ object.customer_name }} <br>
                <i>RMA-No:</i> {{ object.rma }}</h3>
            <input type="submit" value="DELETE" class="btn btn-danger btn-block">
            <a href="{{ object.get_main_root }}" class="btn btn-success btn-block">Abbrechen</a>
        </form>
    </div>
</div>
{% endblock %}