allSales/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from . import settings
from .views import MainView

urlpatterns = [
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^rma/', include('rma.urls', namespace='rma')),
    url(r'^prio/', include('prioListe.urls', namespace='pListe')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^statistic/', include('statistic.urls', namespace='statistic')),
    url(r'^warranty/', include('warranty.urls', namespace='warranty')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rma/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from allSales import settings
from . import views
from .views import RefurbishmentFormView
from .views import RefurbishmentUpdateView
from .views import RMADelete

app_name = 'rma'
urlpatterns = [
    url(r'^$', views.refurbishment_list, name='home'),
    url(r'^create/$', RefurbishmentFormView.as_view(), name='create'),
    url(r'^update/(?P<pk>[\d]+)$', RefurbishmentUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>[\d+]+)$', RMADelete.as_view(), name='delete'),
    url(r'^search/$', views.search_customer, name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

warranty/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from .views import WarrantyFormView
from .views import WarrantyList
from .views import WarrantyUpdateView
from .views import WarrantyDelete

app_name = 'warranty'
urlpatterns = [
    url(r'^$', WarrantyList.as_view(), name='home'),
    url(r'^create/$', WarrantyFormView.as_view(), name='create'),
    url(r'^update/(?P<pk>[\d]+)$', WarrantyUpdateView.as_view(), name='update'),
    url(r'^save_delete/(?P<pk>[\d]+)$', WarrantyDelete.as_view(), name='save_delete'),
    url(r'^search/$', views.search_customer, name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

warranty/models.py
from customer.models import Vasdevice
from allSales.settings import MEDIA_ROOT
from django.core.files import File
from django.db import models
from django.urls import reverse
from django.utils.datetime_safe import datetime

from collar.models import Staff

staffs = Staff.objects.all()

STAFFCHOICES = [
    ('', ''),
]
for staff in staffs:
    STAFFCHOICES.append((staff.name, staff.name))


def file_upload_path(instance, filename):
    return '/'.join(['media', instance.contact_person.name, filename])


# Create your models here.
class Warranty(models.Model):
    class Meta:
        app_label = 'warranty'
        managed = True
        ordering = ['-date']

    date = models.DateField(default=datetime.today())
    contact_person = models.ForeignKey(Staff, null=True)
    customer_collar = models.ManyToManyField(Vasdevice, null=True, blank=True)
    comment = models.TextField(max_length=200)
    date_delivery = models.TextField(max_length=200)
    date_complaint = models.TextField(max_length=200)
    date_collar_failure = models.TextField(max_length=200)
    description_failure = models.TextField(max_length=255)
    following_action = models.TextField(max_length=255)
    replacement = models.TextField(max_length=100)
    deleted = models.BooleanField(default=False)
    warranty_file = models.FileField(null=True, blank=True, upload_to=file_upload_path)
    lifetime = models.CharField(blank=True, null=True, max_length=255, editable=False)
    # failure_describtion = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.description_failure

    def get_main_root(self):
        return reverse('warranty:home')

    def get_labelname(self):
        return 'To Warranty-List'

    def get_update_url(self):
        return reverse('warranty:update',
                       kwargs={'pk': self.pk})

    def get_update_deleted_url(self):
        return reverse('warranty:save_delete',
                       kwargs={'pk': self.pk})

    def get_customer_collar(self):
        liste = list()
        if self.customer_collar is not None and 'test' not in self.description_failure:
            collars = self.customer_collar.all()
            for collar in collars:
                liste.append(collar.producttype)
        return liste

    def save(self, *args, **kwargs):
        if '-' in self.date_delivery:
            self.date_delivery = self.date_delivery.replace('-', '.')
        if '-' in self.date_collar_failure:
            self.date_collar_failure = self.date_collar_failure.replace('-', '.')
        try:
            days_ = datetime.strptime(self.date_collar_failure, '%d.%m.%Y') - datetime.strptime(self.date_delivery, '%d.%m.%Y')
            days = str(days_).split(' ')
            if int(days[0])//365 > 0 :
                lifetime = f'{int(days[0])//365} yrs, {int(days[0])%365} days'
            else:
                lifetime = f'{days[0]} days'
            self.lifetime = lifetime
        except ValueError:
            pass
        super(Warranty, self).save(*args, **kwargs)

warranty/forms.py
from datetime import datetime

from django import forms

from .models import Warranty


class CustomerForm(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.get_full_name()


class WarrantyForm(forms.ModelForm):
    class Meta:
        model = Warranty
        exclude = ('date_complaint', 'deleted')
        help_texts = {
            'customer_collar': 'Please hold down ctrl/strg or for Mac command to select multiple entries',
        }
        widgets = {
            'customer_collar': forms.SelectMultiple(attrs={'class': 'radio1',
                                                        'size': 20, 'required': False}),
        }
        help_texts = {
            'date_delivery': 'Use yyyy-mm-dd as date format',
            'date_collar_failure': 'Use yyyy-mm-dd as date format',
        }

    def clean(self):
        pass
        # cleaned_data = super(WarrantyForm, self).clean()
        # date_delivery = cleaned_data.get('date_delivery')
        # date_of_failure = cleaned_data.get('date_collar_failure')
        # try:
        #     datetime.strptime(date_delivery, '%d.%m.%Y')
        # except ValueError:
        #     self.add_error('date_delivery', 'Please use dd.mm.yyyy as date format')
        # try:
        #     datetime.strptime(date_of_failure, '%d.%m.%Y')
        # except ValueError:
        #     self.add_error('date_collar_failure', 'Please use dd.mm.yyyy as date format')


class WarrantyUpdateForm(forms.ModelForm):
    class Meta:
        model = Warranty
        exclude = ('date', 'contact_person', 'custom_collar', 'deleted')
        help_texts = {
            'customer_collar': 'Please hold down ctrl/strg or for Mac command to select multiple entries',
        }
        widgets = {
            'customer_collar': forms.SelectMultiple(attrs={'class': 'radio1',
                                                           'size': 20, 'required': False}),
        }
        help_texts = {
            'date_delivery': 'Use dd.mm.yyyy as date format',
            'date_collar_failure': 'Use dd.mm.yyyy as date format',
        }

    def clean(self):
        pass
        # cleaned_data = super(WarrantyUpdateForm, self).clean()
        # date_delivery = cleaned_data.get('date_delivery')
        # date_of_failure = cleaned_data.get('date_collar_failure')
        # try:
        #     datetime.strptime(date_delivery, '%d.%m.%Y')
        # except ValueError:
        #     self.add_error('date_delivery', 'Please use dd.mm.yyyy as date format')
        # try:
        #     datetime.strptime(date_of_failure, '%d.%m.%Y')
        # except ValueError:
        #     self.add_error('date_collar_failure', 'Please use dd.mm.yyyy as date format')

warranty/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView

from prioListe.utils import searching
from .forms import WarrantyForm
from .forms import WarrantyUpdateForm
from .models import Warranty


class WarrantyFormView(CreateView):
    form_class = WarrantyForm
    template_name = 'w_form.html'

    def get_success_url(self):
        return reverse('warranty:home')

    def form_valid(self, form):
        return super(WarrantyFormView, self).form_valid(form)


class WarrantyUpdateView(UpdateView):
    model = Warranty
    form_class = WarrantyUpdateForm
    template_name = 'w_form.html'

    def get_success_url(self):
        return reverse('warranty:home')

    def form_valid(self, form):
        return super(WarrantyUpdateView, self).form_valid(form)


class WarrantyList(ListView):
    model = Warranty
    template_name = 'w_list.html'
    queryset = Warranty.objects.filter(deleted=False)

    def get_context_data(self, **kwargs):
        return super(WarrantyList, self).get_context_data(**kwargs)


def search_customer(request):
    if request.method == 'POST':
        search_string = request.POST.get('searchfield')
        t = searching(Warranty, search_string)
        customer_list = Warranty.objects.none()
        for i in t:
            customer_list = i | customer_list  # merge Querysets
        context = {
            'object_list': customer_list.filter(deleted=False)
        }
    return render(request, 'w_list.html', context=context)


class WarrantyDelete(DeleteView):
    model = Warranty
    template_name = 'w_notice_delete.html'
    success_url = reverse_lazy('warranty:home')

warranty/templates/w_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Warranty List</title>
    <link rel="icon" href="http://dev.vectronic-aerospace.com/wp-content/uploads/2016/04/logo180.gif">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css">

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css">

    <style>
        .textareas {
            margin-top: -13%;
        }
        .img-check {
            max-width: 7.8%;
        }
        .img-leer {
            width: 7.5%;
        }
        .own-btn {

        }
        .img-hidden {
            max-width: 7.8%;
        }
    </style>
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}
</body>
</html>

warranty/templates/w_form.html
{% extends 'w_base.html' %}
{% block content %}
<div class="container" style="margin-top:4%">
    <row>
        <h2 id="infotext">
            {% for collar in object.customer_collar.all %}
                {{ collar.serialno|wordwrap:10|linebreaksbr }},
            {% endfor %}
        </h2>
        <form method="post" action="" class="row" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-4">
                    {% if field.errors %}
                        <h4 style="color: chocolate">
                            {% for error in field.errors %}
                                {{ error|safe }}
                            {% endfor %}
                        </h4>
                    {% endif %}
                    <label style="display:block">{{ field.label }}{% if field.help_text %} - {{ field.help_text|safe }}
                    {% endif %}</label>
                    {{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary btn-lg btn-block">
            <a href="{% url 'warranty:home'%}" class="btn btn-secondary btn-lg btn-block">Back</a>
        </form>
    </row>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){

        var myArr = [];
        var myText = '';

        $('#id_customer_collar option').click(function(){

            if($('#id_customer_collar option:checked').length < 2) {
                myArr = [];
            }

            if($(this).hasClass('checked')) {
                $(this).removeClass('checked');
                myArr[$.inArray($(this).text(), myArr)] = '';

            }else {
                if($.inArray($(this).text(), myArr) < 0) {
                    myArr.push($(this).text());
                    $(this).addClass('checked');
                }
            }

            myText = '';
            $('#infotext').empty();

        }).click(function(){
            $('#infotext').empty();
            myArr.forEach(function(item) {
                myText += item;
            });
            $('#infotext').text(myText);
        });

    });
</script>
{% endblock %}

warranty/templates/w_list.html
{% extends 'w_base.html' %}
{% load i18n %}
{% block content %}
    <div class="container-fluid">
        <p><a href="{% url 'warranty:create' %}" class="btn btn-default">Neuen Eintrag erstellen</a>
            <span>Autoreload: </span><button id="refresh" class="btn btn-primary" >off</button>
            <span><a href="{% url 'main' %}" class="btn btn-info btn-sm" style="float:right">Back to Main-Page</a></span>
            <form action="{% url 'warranty:search' %}" method="post">
                {% csrf_token %}
                <input type="text" name="searchfield">
                <input type="submit" class="btn btn-primary btn-sm" value="Search">
                <a href="{% url 'warranty:home' %}" class="btn btn-secondary btn-sm">Clear</a>
            </form>
        </p>
        <div class="col-md-offset-11 col-lg-offset-11 col-md-1 col-lg-1" style="z-index: 2">
            <button id="back-to-top" class="btn btn-info" style="position: fixed; margin-top:30%;">To Top</button>
        </div>
        <table id="demo-table" class="table table-bordered tablesorter">
            <thead>
            <tr>
                    <th>Date</th>
                    <th>Collar ID</th>
                    <th>Contact Person</th>
                    <th>Customer Name</th>
                    <th>Comment</th>
                    <th>Collar Type</th>
                    <th>Customer<br>Country</th>
                    <th>Date of delivery</th>
                    <th>Date of collar failure</th>
                    <th>Lifetime</th>
                    <th>Date of complaint</th>
                    <th>Description of failure</th>
                    <th>Following action</th>
                    <th>Repla<br>cement<br>Yes/No</th>
                    <th>File</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr style="{% cycle 'background-color:#D3D3D3' '' %}">
                    <td style="width:5%">{{ object.date|wordwrap:20|linebreaksbr }}</td>
                    <td style="width:5%">{% for collar in object.customer_collar.all %}
                            {{ collar.serialno|wordwrap:10|linebreaksbr }},
                        {% endfor %}</td>
                    <td style="width:4%">{{ object.contact_person|wordwrap:20|linebreaksbr }}</td>
                    <td style="width:14%">{% for collar in object.customer_collar.all %}
                        {% if forloop.first %}
                            {{ collar.customer}} /
                            {{ collar.customerorganization }}
                        {% endif %}
                        {% endfor %}</td>
                    <td>{{ object.comment|wordwrap:15|linebreaksbr }}</td>
                    <td>{% for collar in object.customer_collar.all %}
                        {% if forloop.first %}
                            {{ collar.producttype|wordwrap:15|linebreaksbr }}
                        {% endif %}
                        {% endfor %}</td>
                    <td style="width:5%">
                        {% for collar in object.customer_collar.all %}
                        {% if forloop.first %}
                            {{ collar.customercountry|wordwrap:15|linebreaksbr }}
                        {% endif%}
                        {% endfor %}</td>
                    <td>{{ object.date_delivery|wordwrap:30|linebreaksbr }}</td>
                    <td>{{ object.date_collar_failure }}</td>
                    <td>{{ object.lifetime }}</td>
                    <td>{{ object.date_complaint|wordwrap:30|linebreaksbr }}</td>
                    <td>{{ object.description_failure|wordwrap:20|linebreaksbr }}</td>
                    <td>{{ object.following_action|wordwrap:25|linebreaksbr }}</td>
                    <td>{{ object.replacement|wordwrap:25|linebreaksbr }}</td>
                    <td>{% if object.warranty_file %}
                            <a href="/media/{{ object.warranty_file }}">X</a>
                        {% endif %}
                    </td>
                    <td><a class="own-btn" href="{{ object.get_update_url }}">Edit</a></td>
                    <td><a class="own-btn btn-danger" href="{{ object.get_update_deleted_url }}">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function() {
        setTimeout("document.location.reload();", 300000);
        $("#demo-table").tablesorter();

    });
</script>

<script>
    $(document).ready(function() {

        $('#back-to-top').hide();
        $(document).mousemove(function(e) {
            if ($(document).scrollTop() > 300) {
                $('#back-to-top').show();
            } else {
                $('#back-to-top').hide();
            }
        });

        $('#back-to-top').click(function(){
            $("html, body").animate({ scrollTop: 0 }, 10);
            return false;
        });

        $('#refresh').click(function() {
            var auto = $('#refresh').html().trim();
            if (auto == 'off') {
                $('#refresh').html('on');
                window.location.href='#stop';
                window.location.href.reload();
            } else {
                $('#refresh').html('off');
                window.location.href = '#';
                setInterval(function() {
                  window.location.href.reload();
                }, 300000);
            }
      });
    });

    (function(){
        if (window.location.hash == '') {
            setInterval(function() {
                  window.location.href.reload();
                }, 300000);
        } else {
            $('#refresh').html('on');
            setInterval(function() {
                  alert('Autoreload ist aus');
                }, 300000);
        }
    }());
</script>
{% endblock %}

warranty/templates/w_notice_delete.html
{% extends 'rma_base.html' %}
{% block title %}
    <title>RMA</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-sm-12 col-md-7 col-lg-7" style="margin-top: 10em;">
        <h2>Are you sure you want <b>DELETE</b> <i>{{ object }}</i></h2>
        <form method="post" class="form-group">
            {% csrf_token %}
            <h3><i>Kunde:</i> {{ object.customer_collar.customer }} <br>
                <i>Comment:</i> {{ object.comment }}</h3>
            <input type="submit" value="DELETE" class="btn btn-danger btn-block">
            <a href="{{ object.get_main_root }}" class="btn btn-success btn-block">Abbrechen</a>
        </form>
    </div>
</div>
{% endblock %}